spring:
  datasource:
    url: jdbc:mysql://198.37.120.210:3306/gizmolk_springboot
    username: gizmolk_support
    password: BANK5155ks@1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true